#!/usr/bin/env python

#Script to use the Mettler Toledo Quantos dispensing system with ROS

import rospy
import sys
from mettler_toledo_quantos_q2_driver import QuantosDriverROS

if __name__ == "__main__": #Object oriented initialization for ROS
    if len(sys.argv) > 1:
        serial_port = sys.argv[1]
    else:
        serial_port = '/dev/ttyUSB0'
        rospy.logwarn('No input serial port is provided. The default serial port (ttyUSB0) is used')
    rospy.init_node("Quantos_Driver", anonymous=True) #initialize rospy node
    Quantos_ROS = QuantosDriverROS(serial_port) #Create instance of ROS Wrapper
    rospy.spin()
